let date = 0

document.getElementById('button').addEventListener('click', button)

function button () {
  document.getElementById('good').style.color = 'green'
  document.getElementById('bad').style.color = 'red'
  date = document.getElementById('input').value
  parseInt(date)
  if (date >= 51) {
    document.getElementById('good').innerHTML = (' in 1970, the famous apollo 13 mission was ago, it was April 11th, 1970, when the spaceship was first launched, and on April 17th, 1970, is when it first made contact on the moon, making it one of the most significant breakthroughs in space travel! ')
    document.getElementById('bad').innerHTML = (' One bad thing that happened in 1970, was that President, Richard Nixon, ordered and invasion in Cambodia, which made the Vietnam war, significantly worse. ')
  } else if (date >= 50) {
    document.getElementById('good').innerHTML = ('This year was known to be one of the years that started the digital age due to the reason that the microprocessor was first invented.')
    document.getElementById('bad').innerHTML = ('This is not a bad fact, but this was the year that a bad man, who was a famous serial killer, Charles Manson, was arrested, and where he was put in jail.')
  } else if (date >= 49) {
    document.getElementById('good').innerHTML = ('There was a New Space Shuttle program that was released to the general public, which would help humans take leaps in the space industry.')
    document.getElementById('bad').innerHTML = ('This year had many significant earthquakes in Nicaragua, Turkey, Iraq, and many other tragedies like terrorist attacks in Isreal!')
  } else if (date >= 48) {
    document.getElementById('good').innerHTML = ('The Famous Skylab is launched, and also the sears tower is done construction, and this is also the year that President Richard Nixon starts his second term as president.')
    document.getElementById('bad').innerHTML = ('Spiro Agnew, who was vice president of America, resigned from his Vice President, Roll.')
  } else if (date >= 47) {
    document.getElementById('good').innerHTML = ('The Soviet Union, launches one of there space stations, which is called the Salyut-4 Space Station, and famous author Stephen King, published his debut Book!')
    document.getElementById('bad').innerHTML = ('President Richard Nixon, resignes due to a famous watergate scandal that arose during his Presidency!')
  } else if (date >= 46) {
    document.getElementById('good').innerHTML = ('The Vietnam war Finally came to a close, on April 30th, Egypt reopened the Suez Canal, after 8 years of closure, which helped the worlds global trade significantly!')
    document.getElementById('bad').innerHTML = ('Cambodia, and South Vietnam, both fell into communism, which was a loss of years of hard work, making some aspects of the Vietnam war useless, and it basically revoked almost all of their progress.')
  } else if (date >= 45) {
    document.getElementById('good').innerHTML = ('Jimmy Carter was Elected President, Conrail began, and also the famous Viking 2 Landed on mars, making its touchdown September 3rd!')
    document.getElementById('bad').innerHTML = ('This was the year, the famous Axe Murder Incident happened in North Korea, which was shocking and scary for some at the time.')
  } else if (date >= 44) {
    document.getElementById('good').innerHTML = ('Space Mountain in Disneyland opens, and to this day, it is still the most popular attraction for Disneyland!')
    document.getElementById('bad').innerHTML = ('The Aeroflot Ilyushin plane crash in Cuba, killing 69 people, and also a demonstration and coup attempt in Angola takes place which afterwards thousands were killed by of Cuban Forces. ')
  } else if (date >= 43) {
    document.getElementById('good').innerHTML = ('Smallpox was finally eradicated, which means it was put to an end, saving and helping hundreds of thousands of people that could have been affected by it in the future!')
    document.getElementById('bad').innerHTML = ('Aldo Moro, who was thought by many to be kidnapped, was killed, he was and italian statesman, and he was also the 38th Prime minister od italy.')
  } else if (date >= 42) {
    document.getElementById('good').innerHTML = ('Jimmy Carter, who was Americas president at the time, finally came to an agreement with Leonid Brezhnev, and they signed the SALT II Agreenment')
    document.getElementById('bad').innerHTML = ('A Nicaraguan National Guard soilder killed ABC TV reporter, Bill Stewart, and his interpreter Juan Espinosa. ')
  } else if (date >= 41) {
    document.getElementById('good').innerHTML = ('good11')
    document.getElementById('bad').innerHTML = ('bad11')
  } else if (date >= 40) {
    document.getElementById('good').innerHTML = ('good12')
    document.getElementById('bad').innerHTML = ('bad12')
  } else if (date >= 39) {
    document.getElementById('good').innerHTML = ('good13')
    document.getElementById('bad').innerHTML = ('bad13')
  } else if (date >= 38) {
    document.getElementById('good').innerHTML = ('good14')
    document.getElementById('bad').innerHTML = ('bad14')
  } else if (date >= 37) {
    document.getElementById('good').innerHTML = ('good15')
    document.getElementById('bad').innerHTML = ('bad15')
  } else if (date >= 36) {
    document.getElementById('good').innerHTML = ('good16')
    document.getElementById('bad').innerHTML = ('bad16')
  } else if (date >= 35) {
    document.getElementById('good').innerHTML = ('good17')
    document.getElementById('bad').innerHTML = ('bad17')
  } else if (date >= 34) {
    document.getElementById('good').innerHTML = ('good18')
    document.getElementById('bad').innerHTML = ('bad18')
  } else if (date >= 33) {
    document.getElementById('good').innerHTML = ('good19')
    document.getElementById('bad').innerHTML = ('bad19')
  } else if (date >= 32) {
    document.getElementById('good').innerHTML = ('good20')
    document.getElementById('bad').innerHTML = ('bad20')
  } else if (date >= 31) {
    document.getElementById('good').innerHTML = ('good21')
    document.getElementById('bad').innerHTML = ('bad21')
  } else if (date >= 30) {
    document.getElementById('good').innerHTML = ('good22')
    document.getElementById('bad').innerHTML = ('bad22')
  } else if (date >= 29) {
    document.getElementById('good').innerHTML = ('good23')
    document.getElementById('bad').innerHTML = ('bad23')
  } else if (date >= 28) {
    document.getElementById('good').innerHTML = ('good24')
    document.getElementById('bad').innerHTML = ('bad24')
  } else if (date >= 27) {
    document.getElementById('good').innerHTML = ('good25')
    document.getElementById('bad').innerHTML = ('bad25')
  } else if (date >= 26) {
    document.getElementById('good').innerHTML = ('good26')
    document.getElementById('bad').innerHTML = ('bad26')
  } else if (date >= 25) {
    document.getElementById('good').innerHTML = ('good27')
    document.getElementById('bad').innerHTML = ('bad27')
  } else if (date >= 24) {
    document.getElementById('good').innerHTML = ('good28')
    document.getElementById('bad').innerHTML = ('bad28')
  } else if (date >= 23) {
    document.getElementById('good').innerHTML = ('good29')
    document.getElementById('bad').innerHTML = ('bad29')
  } else if (date >= 22) {
    document.getElementById('good').innerHTML = ('good30')
    document.getElementById('bad').innerHTML = ('bad30')
  } else if (date >= 21) {
    document.getElementById('good').innerHTML = ('good31')
    document.getElementById('bad').innerHTML = ('bad31')
  }
}
